//! `cargo xtask docs-cli [--check] [--bin FILE]`: `docs/cli/` from the real
//! `toolu` (#442). `toolu commands --json` gives the tree, `--schema` its JSON
//! Schema, and every page holds the real `--help` output, so the help text is
//! the reference. Every generated page starts with `MARKER`; `--check` (the
//! gate's `docs-cli` step) reports stale, missing and orphaned generated files
//! and leaves the hand-written ones (no marker) alone.

mod render;

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::process::Command;

use serde_json::Value;

use crate::options::Options;
use crate::{Verdict, output};

/// Where the generated docs live, relative to the repository root.
pub(crate) const DOCS_DIR: &str = "docs/cli";

/// The first line of every generated Markdown page.
pub(crate) const MARKER: &str =
  "<!-- Generated by cargo xtask docs-cli from toolu commands --json and --help; do not edit. -->";

/// Write `docs/cli/`, or compare it under `--check`.
pub(crate) fn run(options: &Options) -> Result<Verdict, String> {
  if options.check {
    return check(options);
  }
  write(&options.root.join(DOCS_DIR), &expected(options)?)
}

/// Compare `docs/cli/` with what the binary produces: the gate's `docs-cli` step.
pub(crate) fn check(options: &Options) -> Result<Verdict, String> {
  let found = differences(&options.root.join(DOCS_DIR), &expected(options)?)?;
  Ok(output::findings("docs-cli", &found))
}

/// Every generated file and its content, from the binary `--bin` names or cargo builds.
fn expected(options: &Options) -> Result<BTreeMap<String, String>, String> {
  let bin = match &options.bin {
    Some(bin) => bin.clone(),
    None => build(&options.root)?,
  };
  let toolu = |args: &[&str]| capture(&bin, args);
  let tree_text = toolu(&["commands", "--json"])?;
  let tree: Value = serde_json::from_str(&tree_text)
    .map_err(|err| format!("toolu commands --json printed unreadable JSON: {err}"))?;
  let mut files = render::pages(&tree, &toolu)?;
  files.insert(
    "commands.json".to_owned(),
    format!("{}\n", tree_text.trim_end()),
  );
  let schema = toolu(&["commands", "--schema"])?;
  files.insert(
    "commands.schema.json".to_owned(),
    format!("{}\n", schema.trim_end()),
  );
  Ok(files)
}

/// Build `toolu-cli` in `root` and return the `toolu` executable cargo reports.
fn build(root: &Path) -> Result<PathBuf, String> {
  let cargo = std::env::var_os("CARGO").unwrap_or_else(|| "cargo".into());
  let built = Command::new(cargo)
    .args(["build", "--locked", "--quiet", "-p", "toolu-cli"])
    .arg("--message-format=json")
    .current_dir(root)
    .output()
    .map_err(|err| format!("cannot run cargo build: {err}"))?;
  if !built.status.success() {
    return Err(format!(
      "cargo build -p toolu-cli failed: {}",
      String::from_utf8_lossy(&built.stderr).trim()
    ));
  }
  String::from_utf8_lossy(&built.stdout)
    .lines()
    .filter_map(|line| serde_json::from_str::<Value>(line).ok())
    .filter(|message| message.pointer("/target/name") == Some(&Value::from("toolu")))
    .find_map(|message| message.get("executable")?.as_str().map(PathBuf::from))
    .ok_or_else(|| "cargo build -p toolu-cli reported no toolu executable".to_owned())
}

/// The stdout of `bin args`, which must exit 0.
fn capture(bin: &Path, args: &[&str]) -> Result<String, String> {
  let shown = format!("{} {}", bin.display(), args.join(" "));
  let ran = Command::new(bin)
    .args(args)
    .output()
    .map_err(|err| format!("cannot run {shown}: {err}"))?;
  if !ran.status.success() {
    return Err(format!(
      "{shown} exited {}: {}",
      ran.status,
      String::from_utf8_lossy(&ran.stderr).trim()
    ));
  }
  String::from_utf8(ran.stdout).map_err(|err| format!("{shown} printed non-UTF-8 output: {err}"))
}

/// One finding per generated file that is missing, stale or orphaned in `dir`.
fn differences(dir: &Path, files: &BTreeMap<String, String>) -> Result<Vec<String>, String> {
  let mut found = Vec::new();
  for (name, content) in files {
    match std::fs::read_to_string(dir.join(name)) {
      Ok(text) if text == *content => {}
      Ok(_) => found.push(format!(
        "{DOCS_DIR}/{name}: stale — run `cargo xtask docs-cli`"
      )),
      Err(_) => found.push(format!(
        "{DOCS_DIR}/{name}: missing or unreadable — run `cargo xtask docs-cli`"
      )),
    }
  }
  for name in orphans(dir, files)? {
    found.push(format!(
      "{DOCS_DIR}/{name}: orphaned generated page — run `cargo xtask docs-cli`"
    ));
  }
  Ok(found)
}

/// Generated pages in `dir` (their first line is `MARKER`) that `files` no longer has.
fn orphans(dir: &Path, files: &BTreeMap<String, String>) -> Result<Vec<String>, String> {
  let entries = match std::fs::read_dir(dir) {
    Ok(entries) => entries,
    Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Ok(Vec::new()),
    Err(err) => return Err(format!("cannot list {}: {err}", dir.display())),
  };
  let mut found = Vec::new();
  for entry in entries {
    let entry = entry.map_err(|err| format!("cannot list {}: {err}", dir.display()))?;
    let name = entry.file_name().to_string_lossy().into_owned();
    let generated =
      std::fs::read_to_string(entry.path()).is_ok_and(|text| text.lines().next() == Some(MARKER));
    if generated && !files.contains_key(&name) {
      found.push(name);
    }
  }
  found.sort();
  Ok(found)
}

/// Write `files` into `dir` and delete the orphaned generated pages.
fn write(dir: &Path, files: &BTreeMap<String, String>) -> Result<Verdict, String> {
  std::fs::create_dir_all(dir).map_err(|err| format!("cannot create {}: {err}", dir.display()))?;
  for name in orphans(dir, files)? {
    std::fs::remove_file(dir.join(&name))
      .map_err(|err| format!("cannot remove {DOCS_DIR}/{name}: {err}"))?;
  }
  for (name, content) in files {
    std::fs::write(dir.join(name), content)
      .map_err(|err| format!("cannot write {DOCS_DIR}/{name}: {err}"))?;
  }
  output::say(&format!(
    "docs-cli: wrote {} files to {DOCS_DIR}",
    files.len()
  ));
  Ok(Verdict::Clean)
}

#[cfg(test)]
#[path = "tests/docs_cli_test.rs"]
mod tests;
