/**
 * The inline ast-grep rules (#265), verbatim from 78-error-ast.sh and
 * 85-no-mocks.sh. Severity is `warning` on purpose: `scan` exits non-zero on an
 * error-level match, which would be indistinguishable from a crashed tool.
 */

/** Error-handling rules: swallowed errors, silent rejections, non-Error throws. */
export const ERROR_RULES =
  "id: empty-catch\nlanguage: ts\nseverity: warning\nmessage: empty catch\nrule:\n  pattern: 'try { $$$ } catch ($_) { }'\n---\nid: empty-catch-noarg\nlanguage: ts\nseverity: warning\nmessage: empty catch (no binding)\nrule:\n  pattern: 'try { $$$ } catch { }'\n---\nid: empty-catch-handler\nlanguage: ts\nseverity: warning\nmessage: empty promise catch handler\nrule:\n  pattern: '$_.catch(() => { })'\n---\nid: null-catch-handler\nlanguage: ts\nseverity: warning\nmessage: promise catch handler returning null\nrule:\n  pattern: '$_.catch(() => null)'\n---\nid: undef-catch-handler\nlanguage: ts\nseverity: warning\nmessage: promise catch handler returning undefined\nrule:\n  pattern: '$_.catch(() => undefined)'\n---\nid: swallow-null-arg\nlanguage: ts\nseverity: warning\nmessage: catch returns null\nrule:\n  pattern: 'try { $$$ } catch ($_) { return null }'\n---\nid: swallow-undef-arg\nlanguage: ts\nseverity: warning\nmessage: catch returns undefined\nrule:\n  pattern: 'try { $$$ } catch ($_) { return undefined }'\n---\nid: swallow-null\nlanguage: ts\nseverity: warning\nmessage: catch returns null (no binding)\nrule:\n  pattern: 'try { $$$ } catch { return null }'\n---\nid: swallow-undef\nlanguage: ts\nseverity: warning\nmessage: catch returns undefined (no binding)\nrule:\n  pattern: 'try { $$$ } catch { return undefined }'\n---\n# A bare `return` in an ast-grep pattern acts as a WILDCARD over the optional\n# argument: `catch { return }` also matched `return []`, `return 42` and\n# `return null`, i.e. every non-nullish fallback got reported as \"returns a\n# nullish value\". Match the catch clause itself, then require that its single\n# return statement carries no argument at all.\nid: swallow-bare\nlanguage: ts\nseverity: warning\nmessage: catch returns nothing\nrule:\n  all:\n    - any:\n        - pattern:\n            context: 'try {} catch { return }'\n            selector: catch_clause\n        - pattern:\n            context: 'try {} catch ($_) { return }'\n            selector: catch_clause\n    - not:\n        has:\n          stopBy: end\n          kind: return_statement\n          has:\n            stopBy: neighbor\n            pattern: $X\n---\nid: throw-empty-error\nlanguage: ts\nseverity: warning\nmessage: throw new Error() with no message\nrule:\n  pattern: 'throw new Error()'\n---\nid: throw-string\nlanguage: ts\nseverity: warning\nmessage: throw of a string literal\nrule:\n  pattern: 'throw \"$S\"'\n---\nid: throw-template\nlanguage: ts\nseverity: warning\nmessage: throw of a template literal\nrule:\n  pattern: 'throw `$S`'";

/** Mock-call rules for test files. */
export const MOCK_RULES =
  "id: jest-mock\nlanguage: ts\nseverity: warning\nmessage: jest.mock() call\nrule:\n  pattern: jest.mock($$$)\n---\nid: vi-mock\nlanguage: ts\nseverity: warning\nmessage: vi.mock() call\nrule:\n  pattern: vi.mock($$$)\n---\nid: jest-fn\nlanguage: ts\nseverity: warning\nmessage: jest.fn() call\nrule:\n  pattern: jest.fn($$$)\n---\nid: vi-fn\nlanguage: ts\nseverity: warning\nmessage: vi.fn() call\nrule:\n  pattern: vi.fn($$$)\n---\nid: sinon-method\nlanguage: ts\nseverity: warning\nmessage: sinon mock method call\nrule:\n  pattern: sinon.$M($$$)";
