#!/usr/bin/env bats
# Guards the vendored pricing copy in the statusline plugin against drift from
# the canonical stats source. The two plugins install under separate
# CLAUDE_PLUGIN_ROOTs and CANNOT share code at runtime, so the math is vendored
# (plugins/statusline/hooks/pricing-vendored.sh, regenerated by
# plugins/statusline/scripts/sync-pricing.sh). This test fails the build if the
# vendored copy diverges from the source — editing a rate in one place without
# regenerating the other is caught here.

setup() {
  STATS="${BATS_TEST_DIRNAME}/../../stats/scripts/lib/pricing.sh"
  VEND="${BATS_TEST_DIRNAME}/../hooks/pricing-vendored.sh"
  LEDGER="${BATS_TEST_DIRNAME}/../hooks/token-ledger.sh"
}

@test "vendored pricing prelude is byte-identical to the canonical stats source" {
  a="$(source "$STATS"; stats_pricing_jq)"
  b="$(source "$VEND"; _tl_pricing_jq)"
  [ "$a" = "$b" ]
}

@test "token-ledger uses the vendored prelude, not its own inlined rates()/cost" {
  ! grep -q 'def rates(' "$LEDGER"
  ! grep -q 'def msgcost(' "$LEDGER"
  grep -q 'pricing-vendored.sh' "$LEDGER"
  grep -q 'msgcost(\$u; \$r)' "$LEDGER"
}

@test "the byte-identity check actually fails on a tampered rate (guard is live)" {
  a="$(source "$STATS"; stats_pricing_jq | sed 's/i: 10, o: 50/i: 99, o: 99/')"
  b="$(source "$VEND"; _tl_pricing_jq)"
  [ "$a" != "$b" ]
}

@test "sync-pricing.sh regenerates a byte-identical copy (idempotent)" {
  tmp="$BATS_TEST_TMPDIR/vendored.sh"
  cp "$VEND" "$tmp"
  bash "${BATS_TEST_DIRNAME}/../scripts/sync-pricing.sh" >/dev/null
  diff "$tmp" "$VEND"          # regeneration produced no change → in sync
}
